version: "3.9"
services:
  api:
    container_name: base-api-dev
    image: base-api
    build:
      context: .
      dockerfile: Dockerfile_air
    volumes:
      - ./:/api
    env_file:
      - .env.dev
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@base-database-dev/${POSTGRES_DB}?sslmode=disable
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    ports:
      - ${PORT}:${PORT}
      - 2345:2345
    depends_on:
      - database
    command: air