FROM golang:1.17-alpine

WORKDIR /api
COPY . .

RUN apk --no-cache add curl build-base

# Install Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Install Air
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

# Install golang-migrate
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz && \
    mv migrate.linux-amd64 $GOPATH/bin/migrate

EXPOSE ${PORT}
