name: Quality Assurance

on: [ push ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run linters
        run: make qa/lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: make qa/coverage

      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v2
